name: "piel-coverage"

on:
  workflow_dispatch:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1    # Get colored pytest output

permissions:
  contents: read

jobs:
  build:
    name: Coverage Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:  # Set environment variables for the whole job
      PIP_ONLY_BINARY: gdstk
      MPLBACKEND: agg
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
        virtualenvs-create: true
        virtualenvs-in-project: true
    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      run: poetry install -E dev
    #----------------------------------------------
    #    add matrix specifics and run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        source $VENV
        coverage run -m pytest -rA tests
        coverage report -m
        echo "total=$(coverage report --format=total)" >> $GITHUB_ENV
        echo '### Total coverage: ${{ env.total }}%'

    - name: "Create badge"
      # if: ${{ github.ref == 'refs/heads/latest' }}
      # https://gist.githubusercontent.com/nedbat/8c6980f77988a327348f9b02bbaf67f5
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GH_PAT }}
        gistID: 605df9da19061593715258b77e06ab9b
        filename: piel_coverage.json
        label: Coverage
        message: ${{ env.total }}%
        minColorRange: 60
        maxColorRange: 95
        valColorRange: ${{ env.total }}
        style: "for-the-badge"
