name: "piel-tests"

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          submodules: 'recursive'
      - name: Test pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run # this should be really more agressive
  build:
    name: test ${{ matrix.python-version }} - ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        platform: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    env:  # Set environment variables for the whole job
      PIP_ONLY_BINARY: gdstk
      MPLBACKEND: agg
    steps:
    - uses: actions/checkout@v4

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    #----------------------------------------------
    # install your root project, if required
    #----------------------------------------------
    - name: Install library
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        poetry --version
        poetry install -E dev
    #----------------------------------------------
    #    add matrix specifics and run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        # poetry run black . --check --diff
        # poetry run ruff check piel --fix --exit-non-zero-on-fix
        poetry run pytest -rA tests
